"""Which chime plays when, and how the CTk app actually plays one.

Three short chimes live in content/sounds/ (generated by
scripts/generate_sounds.py, pure sine-wave synthesis, no external asset):
success_chime (a lesson passed), badge_unlock (a new badge), and level_up
(the player's XP level went up). success_sound_for() is the shared,
UI-agnostic decision of which sound(s) a given lesson-success moment should
play -- reused by both app/ui/lesson_screen.py (CTk) and
app/ui/lesson_screen_flet.py (Flet) so the "level up beats a plain success
chime, badge unlock can layer on top of either" rule lives in one place.

CTk plays sounds directly via the stdlib winsound.PlaySound -- Windows-only,
but so is the CTk build itself (see CLAUDE.md), so that's not a new
limitation. Flet needs its own player (app/ui/components/sound_player_flet.py)
since a plain filesystem call on the server side isn't how audio reaches a
Flet client -- see that module's docstring for why.
"""
from __future__ import annotations

import sys
from pathlib import Path

from app.config.settings import Settings, get_repo_root

SOUND_NAMES = ("success_chime", "badge_unlock", "level_up")

_SOUNDS_DIR = get_repo_root() / "content" / "sounds"


def sound_path(name: str) -> Path:
    if name not in SOUND_NAMES:
        raise ValueError(f"Unknown sound {name!r} -- expected one of {SOUND_NAMES}")
    return _SOUNDS_DIR / f"{name}.wav"


def success_sound_for(*, leveled_up: bool, badge_earned: bool) -> list[str]:
    """Which sound name(s), in play order, for a lesson-success moment.

    A level-up chime takes priority over the plain success chime (it's the
    bigger moment); a badge unlock always gets its own chime layered on
    top of whichever of those two played, since a badge can be earned on
    the same lesson that also happens to level the player up.
    """
    sounds = ["level_up" if leveled_up else "success_chime"]
    if badge_earned:
        sounds.append("badge_unlock")
    return sounds


def play_sound_ctk(name: str, settings: Settings) -> None:
    """Fire-and-forget playback for the CTk app. No-ops quietly if sound
    is disabled, the platform isn't Windows (winsound is stdlib but
    Windows-only), or the file is missing -- a missing/disabled sound
    should never be a reason a lesson can't be completed."""
    if not settings.sound_enabled or sys.platform != "win32":
        return
    path = sound_path(name)
    if not path.is_file():
        return
    import winsound  # Windows-only stdlib module -- imported lazily so this
    # module still imports cleanly on non-Windows dev/CI machines.

    winsound.PlaySound(str(path), winsound.SND_FILENAME | winsound.SND_ASYNC)
